import React from 'react';

import { injectGlobal } from '@emotion/css';

import {
  BRAND_FONT_FAMILY,
  BRAND_FONT_WOFF2,
  LOCKUP_ASPECT,
  LOCKUP_MARK_PATH,
  LOCKUP_VIEW_BOX,
  LOCKUP_WORD_PATH,
  NIB_CELLS,
} from './brandData';

/**
 * The noise is bad. brand: an 8x8 block of TV static beside "noise / is bad."
 * set in Archivo Black.
 *
 * The data behind it is generated by `design/brand/generate.py` into
 * `brandData.ts`. The fixed lockup is outlined to paths, so it looks identical
 * whether or not a font has loaded and has a known shape that a bouncing mark
 * can be sized from without measuring. Only text a viewer types for the 3D mark
 * needs the real font, which is embedded rather than fetched: a television on a
 * locked-down office network cannot be relied on to reach Google Fonts.
 */

export { LOCKUP_ASPECT };

/** The name the lockup reads as, to anyone who cannot see it. */
export const WORDMARK = 'noise is bad.';

/** Every lit cell as one path in the mark's own 8x8 space. */
export const MARK_PATH = NIB_CELLS.map((on, i) => (on ? `M${i % 8} ${Math.floor(i / 8)}h1v1h-1z` : '')).join('');

/**
 * The mark as a mask image, for surfaces that need painting with something
 * other than a flat colour — the 3D mark's reflection.
 */
export const MARK_MASK = `url("data:image/svg+xml,${encodeURIComponent(
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 8" shape-rendering="crispEdges"><path d="${MARK_PATH}"/></svg>`
)}")`;

/** The 8x8 static on its own, in the current text colour. */
export const StaticMark: React.FC<{ size: number | string }> = ({ size }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 8 8"
    shapeRendering="crispEdges"
    aria-hidden="true"
    focusable="false"
    data-testid="static-mark"
  >
    <path d={MARK_PATH} fill="currentColor" />
  </svg>
);

/** The full lockup, mark and wordmark, in the current text colour. */
export const NibLockup: React.FC<{ width: number; height: number }> = ({ width, height }) => (
  <svg
    width={width}
    height={height}
    viewBox={LOCKUP_VIEW_BOX}
    role="img"
    aria-label={WORDMARK}
    focusable="false"
    data-testid="nib-lockup"
  >
    <title>{WORDMARK}</title>
    <path d={LOCKUP_MARK_PATH} fill="currentColor" shapeRendering="crispEdges" />
    <path d={LOCKUP_WORD_PATH} fill="currentColor" />
  </svg>
);

/** The font stack for brand text. The fallbacks are the nearest heavy grotesques most machines have. */
export const BRAND_TYPEFACE = `"${BRAND_FONT_FAMILY}", "Arial Black", "Helvetica Neue", Helvetica, sans-serif`;

let fontInjected = false;

/**
 * Registers the embedded Archivo Black once per page.
 *
 * Idempotent, and deferred to first use rather than done at import, so loading
 * the plugin costs nothing until a panel actually needs the face.
 */
export function ensureBrandFont(): void {
  if (fontInjected) {
    return;
  }
  fontInjected = true;
  injectGlobal({
    '@font-face': {
      fontFamily: `'${BRAND_FONT_FAMILY}'`,
      src: `url(${BRAND_FONT_WOFF2}) format('woff2')`,
      fontWeight: 400,
      fontStyle: 'normal',
      // Block briefly rather than flash a fallback: the face is inline, so it
      // is ready within a frame and a swap would only be visible as a jolt.
      fontDisplay: 'block',
    },
  });
}

/** The lockup's proportions, in ems of the wordmark's font size. */
export const LOCKUP = {
  lineHeight: 0.92,
  tracking: -0.035,
  /** The mark is a touch shorter than the text block, centred on it: 132px against two 76px lines. */
  markToBlock: 132 / (2 * 76 * 0.92),
  gap: 36 / 76,
};

/**
 * Stacks a line of text the way the lockup stacks "noise / is bad.".
 *
 * Breaks at the space nearest the middle, so the two lines come out close in
 * length, which is what makes the lockup a block rather than a sentence. A
 * single word, or text that already has line breaks, is left alone.
 */
export function stackLines(text: string): string[] {
  if (text.includes('\n')) {
    return text.split('\n');
  }

  const middle = text.length / 2;
  let best = -1;
  for (let i = 0; i < text.length; i++) {
    if (text[i] === ' ' && (best < 0 || Math.abs(i - middle) < Math.abs(best - middle))) {
      best = i;
    }
  }

  return best < 0 ? [text] : [text.slice(0, best), text.slice(best + 1)];
}

/**
 * How big a stacked lockup is, in ems, without laying it out.
 *
 * Measured against Archivo Black with the lockup's tracking: lowercase averages
 * 0.58em a character and capitals 0.73. Rounded up slightly, because guessing
 * high only makes the lockup a little smaller, where guessing low spills it.
 */
export function lockupSize(lines: string[]): { width: number; height: number; mark: number } {
  const lineWidth = (line: string) =>
    [...line].reduce((total, character) => total + (/[A-Z0-9]/.test(character) ? 0.76 : 0.6), 0);

  const block = Math.max(1, lines.length) * LOCKUP.lineHeight;
  const mark = block * LOCKUP.markToBlock;

  return {
    width: mark + LOCKUP.gap + Math.max(0, ...lines.map(lineWidth)),
    height: block,
    mark,
  };
}
