"""
Generates the noise is bad. brand assets from two inputs: the Archivo Black font
and the chosen 8x8 static pattern. Everything it writes is committed, so the
plugin never needs Python, the font file, or a network at build time.

    python3 -m venv .venv && .venv/bin/pip install fonttools brotli uharfbuzz
    .venv/bin/python design/brand/generate.py path/to/ArchivoBlack-Regular.ttf

Outputs:
    src/render/brandData.ts   pattern, outlined lockup paths, embedded font
    src/img/logo.svg          the Grafana plugin logo: the mark on ink
    docs/brand/lockup-dark.svg, lockup-light.svg   for the README
"""
import base64, io, json, sys
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[2]
FONT = Path(sys.argv[1])

# The lockup exactly as the Main artboard drew it: an 8x8 mark beside two lines
# of 76px Archivo Black, line-height 0.92, tracking -0.035em, mark 132px, gap 36px.
LINES = ['noise', 'is bad.']
LINE_HEIGHT = 0.92
TRACKING = -0.035
MARK = 132 / 76
GAP = 36 / 76

INK, PAPER = '#0b0c0e', '#f2f1ed'
CELLS = json.loads((ROOT / 'design/patterns.json').read_text())['balanced']

font = TTFont(FONT)
upem = font['head'].unitsPerEm
ascent, descent = font['hhea'].ascent / upem, -font['hhea'].descent / upem
glyphs = font.getGlyphSet()

# Where a browser puts the baseline inside a line box: half the leading, then the ascent.
baseline0 = (LINE_HEIGHT - (ascent + descent)) / 2 + ascent

face = hb.Face(FONT.read_bytes())
hbfont = hb.Font(face)

U = 1000  # output units per em; paths are written at this scale


def shape(text):
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(hbfont, buf, {'kern': True, 'liga': False})
    return list(zip(buf.glyph_infos, buf.glyph_positions))


text_x = MARK + GAP
paths, ink = [], [float('inf'), float('inf'), float('-inf'), float('-inf')]
for row, line in enumerate(LINES):
    base = baseline0 + row * LINE_HEIGHT
    pen_x = text_x
    for info, pos in shape(line):
        name = font.getGlyphName(info.codepoint)
        # Font units, y up  ->  output units, y down, placed on this baseline.
        t = (U / upem, 0, 0, -U / upem, (pen_x + pos.x_offset / upem) * U, (base - pos.y_offset / upem) * U)
        svg = SVGPathPen(glyphs, ntos=lambda v: ('%.1f' % v).rstrip('0').rstrip('.'))
        glyphs[name].draw(TransformPen(svg, t))
        if svg.getCommands():
            paths.append(svg.getCommands())
        bounds = BoundsPen(glyphs)
        glyphs[name].draw(TransformPen(bounds, t))
        if bounds.bounds:
            x0, y0, x1, y1 = bounds.bounds
            ink = [min(ink[0], x0), min(ink[1], y0), max(ink[2], x1), max(ink[3], y1)]
        # CSS adds letter-spacing after every character, the last one included.
        pen_x += pos.x_advance / upem + TRACKING

block = len(LINES) * LINE_HEIGHT
mark_top = (block - MARK) / 2  # the artboard centred the mark on the text block
cell = MARK / 8

# Tight to what is actually drawn, so a bouncing lockup touches the wall with ink.
top = min(mark_top * U, ink[1])
bottom = max((mark_top + MARK) * U, ink[3])
right = ink[2]
view = [0, round(top, 1), round(right, 1), round(bottom - top, 1)]


def cells_path(size, oy=0.0):
    """One path for every lit cell. Fewer DOM nodes than 32 rects on a television."""
    c = size / 8
    out = []
    for i, on in enumerate(CELLS):
        if on:
            x, y = (i % 8) * c, oy + (i // 8) * c
            out.append('M%s %sh%sv%sh-%sz' % (fmt(x), fmt(y), fmt(c), fmt(c), fmt(c)))
    return ''.join(out)


fmt = lambda v: ('%.2f' % v).rstrip('0').rstrip('.')

mark_path = cells_path(MARK * U, mark_top * U)
word_path = ''.join(paths)

# The font for text a viewer types into the 3D mark: Latin, common punctuation.
opts = Options()
opts.flavor = 'woff2'
opts.layout_features = ['kern', 'liga']
opts.name_IDs = ['*']
opts.notdef_outline = True
# recalcTimestamp off: otherwise every run stamps the time into the font and
# regenerating produces a different file for no reason.
sub = TTFont(FONT, recalcTimestamp=False)
s = Subsetter(opts)
s.populate(unicodes=list(range(0x20, 0x7F)) + list(range(0xA0, 0x100)) +
           [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2026, 0x20AC])
s.subset(sub)
blob = io.BytesIO()
sub.flavor = 'woff2'
sub.save(blob)
woff2 = base64.b64encode(blob.getvalue()).decode()

ts = f'''/**
 * GENERATED by design/brand/generate.py. Do not edit by hand; re-run the script.
 *
 * The noise is bad. brand, as data: the 8x8 static pattern, the lockup outlined
 * to paths, and Archivo Black subset to Latin for text a viewer types.
 *
 * Archivo Black is Copyright 2017 The Archivo Black Project Authors
 * (https://github.com/Omnibus-Type/ArchivoBlack), licensed under the SIL Open
 * Font License 1.1. The licence travels with it in `src/render/fonts/OFL.txt`.
 */

/** Which of the 64 cells are lit, row by row. Exactly 32, no empty row, column or quadrant. */
export const NIB_CELLS: readonly number[] = {json.dumps(CELLS)};

/** The lockup's own coordinate space: {U} units to the em. */
export const LOCKUP_VIEW_BOX = '{' '.join(str(v) for v in view)}';

/** Width over height, so the caller can size by either edge. */
export const LOCKUP_ASPECT = {view[2] / view[3]:.6f};

/** The mark's lit cells, placed where the lockup puts them. */
export const LOCKUP_MARK_PATH = '{mark_path}';

/** "noise / is bad." in Archivo Black, shaped with kerning, tracked -0.035em, line-height 0.92. */
export const LOCKUP_WORD_PATH = '{word_path}';

/** The embedded face's family name. Distinct, so it never collides with a copy the viewer has installed. */
export const BRAND_FONT_FAMILY = 'Noise Is Bad Archivo Black';

/** Archivo Black, Latin subset, WOFF2. */
export const BRAND_FONT_WOFF2 = 'data:font/woff2;base64,{woff2}';
'''
(ROOT / 'src/render/brandData.ts').write_text(ts)

fonts = ROOT / 'src/render/fonts'
fonts.mkdir(exist_ok=True)
(fonts / 'OFL.txt').write_text((FONT.parent / 'OFL.txt').read_text())


def grid_svg(on, off):
    rects = ''.join(f'<rect x="{i % 8}" y="{i // 8}" width="1" height="1"/>' for i, v in enumerate(CELLS) if v)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 8" shape-rendering="crispEdges">'
            f'<title>noise is bad.</title><rect width="8" height="8" fill="{off}"/><g fill="{on}">{rects}</g></svg>\n')


(ROOT / 'src/img/logo.svg').write_text(grid_svg(PAPER, INK))

brand = ROOT / 'docs/brand'
brand.mkdir(parents=True, exist_ok=True)
for name, colour in (('lockup-dark.svg', PAPER), ('lockup-light.svg', INK)):
    (brand / name).write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{" ".join(str(v) for v in view)}" '
        f'width="{round(view[2] / 8)}" height="{round(view[3] / 8)}">'
        f'<title>noise is bad.</title><g fill="{colour}"><path d="{mark_path}" shape-rendering="crispEdges"/>'
        f'<path d="{word_path}"/></g></svg>\n')

print('view', view, 'aspect %.3f' % (view[2] / view[3]))
print('word path %d chars, mark path %d chars' % (len(word_path), len(mark_path)))
print('woff2 %.1f KB, base64 %.1f KB' % (len(blob.getvalue()) / 1024, len(woff2) / 1024))
